export type Game = {
  Match: string,
  Date: string,
  Championnat: string,
  "Journée de championnat": string,
  "Domicile - Nom": string,
  "Domicile - Couleur": string,
  "Domicile - Logo (sm)": string,
  "Domicile - Logo (md)": string,
  "Domicile - Logo (lg)": string,
  "Extérieur - Nom": string,
  "Extérieur - Couleur": string,
  "Extérieur - Logo (sm)": string,
  "Extérieur - Logo (md)": string,
  "Extérieur - Logo (lg)": string,
  Lieu: string,
  Période: string,
  "Domicile - Q1": string,
  "Domicile - Q2": string,
  "Domicile - Q3": string,
  "Domicile - Q4": string,
  "Domicile - OT1": string,
  "Domicile - OT2": string,
  "Domicile - OT3": string,
  "Domicile - Final": string,
  "Extérieur - Q1": string,
  "Extérieur - Q2": string,
  "Extérieur - Q3": string,
  "Extérieur - Q4": string,
  "Extérieur - OT1": string,
  "Extérieur - OT2": string,
  "Extérieur - OT3": string,
  "Extérieur - Final": string
}
